/**
 * Menus for the 7 Indore restaurants, keyed by `menuKey` in restaurants.data.js.
 *
 * Every item goes through item()/category() in menu.builders.js, which derives
 * the display price from the variant ladder and the category's foodTypeScope
 * from its items — so this file cannot express a state the API would reject.
 *
 * Items with a curated `image` use it when the URL is reachable; items with no
 * `image` (or an image that 404s) fall back to the `tag` default in config.js.
 */
import { V, item, category } from './menu.builders.js';

const IMG = {
    paneerTikka: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=80',
    seekhKebab: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&auto=format&fit=crop&q=80',
    butterChicken: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    dalMakhani: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    naan: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800&auto=format&fit=crop&q=80',
    biryani: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    chaat: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    samosa: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=800&auto=format&fit=crop&q=80',
    jalebi: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    gulabJamun: 'https://images.unsplash.com/photo-1666190092159-3171cf0fbb12?w=800&auto=format&fit=crop&q=80',
    lassi: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800&auto=format&fit=crop&q=80',
    chai: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=800&auto=format&fit=crop&q=80',
    coldCoffee: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&auto=format&fit=crop&q=80',
    poha: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&auto=format&fit=crop&q=80',
    paratha: 'https://images.unsplash.com/photo-1633945274309-2c16c9682a8c?w=800&auto=format&fit=crop&q=80',
    thali: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
    margherita: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    pepperoniStyle: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80',
    pasta: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&auto=format&fit=crop&q=80',
    garlicBread: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800&auto=format&fit=crop&q=80',
    fries: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&auto=format&fit=crop&q=80',
    burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    lavaCake: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80',
    tiramisu: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=80',
    momos: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&auto=format&fit=crop&q=80',
    noodles: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=80',
    friedRice: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80',
    manchurian: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&auto=format&fit=crop&q=80',
    soup: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=80',
    thaiCurry: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&auto=format&fit=crop&q=80',
    chole: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=80',
    halwa: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&auto=format&fit=crop&q=80',
    friedChicken: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=80',
    fishTikka: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    raita: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
};

export const MENUS = {
    /* ============================== 1. Sarafa Chaat Junction (veg) ============================== */
    sarafa_chaat: [
        category({
            name: 'Indori Chaat',
            tag: 'chaat',
            image: IMG.chaat,
            items: [
                item({
                    name: 'Indori Garadu Chaat',
                    foodType: 'Veg',
                    price: 89,
                    tag: 'chaat',
                    prepTime: '10-15 mins',
                    description: 'Winter-special fried yam tossed with garadu masala, lemon and rock salt — the Sarafa signature.',
                }),
                item({
                    name: 'Bhutte Ka Kees',
                    foodType: 'Veg',
                    price: 79,
                    tag: 'chaat',
                    prepTime: '10-15 mins',
                    description: 'Grated sweet corn slow-cooked in milk with green chilli, mustard seeds and fresh coriander.',
                }),
                item({
                    name: 'Dahi Bada',
                    foodType: 'Veg',
                    variants: V.pieces(69, [2, 4]),
                    tag: 'chaat',
                    image: IMG.chaat,
                    prepTime: '5-10 mins',
                    description: 'Soft urad dal vadas soaked in chilled sweet curd, topped with tamarind and mint chutney.',
                }),
                item({
                    name: 'Sev Puri',
                    foodType: 'Veg',
                    price: 69,
                    tag: 'chaat',
                    image: IMG.chaat,
                    prepTime: '5-10 mins',
                    description: 'Crisp puris loaded with potato, onion, three chutneys and a generous shower of Indori sev.',
                }),
                item({
                    name: 'Aloo Tikki Chaat',
                    foodType: 'Veg',
                    variants: V.portions(79),
                    tag: 'chaat',
                    prepTime: '10-15 mins',
                    description: 'Griddle-crisped potato tikki broken over white peas, curd and tangy chutneys.',
                }),
                item({
                    name: 'Pani Puri',
                    foodType: 'Veg',
                    variants: V.pieces(49, [6, 12]),
                    tag: 'chaat',
                    prepTime: '5-10 mins',
                    description: 'Semolina puris with spiced potato filling and chilled pudina-jeera pani.',
                }),
            ],
        }),
        category({
            name: 'Kachori & Samosa',
            tag: 'snack',
            image: IMG.samosa,
            items: [
                item({
                    name: 'Khasta Kachori',
                    foodType: 'Veg',
                    variants: V.pieces(45, [2, 4]),
                    tag: 'snack',
                    image: IMG.samosa,
                    prepTime: '10-15 mins',
                    description: 'Flaky kachori stuffed with spiced moong dal, served with tamarind chutney.',
                }),
                item({
                    name: 'Pyaaz Kachori',
                    foodType: 'Veg',
                    variants: V.pieces(49, [2, 4]),
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Rajasthani-style onion kachori with a peppery masala core.',
                }),
                item({
                    name: 'Aloo Samosa',
                    foodType: 'Veg',
                    variants: V.pieces(30, [2, 4]),
                    tag: 'snack',
                    image: IMG.samosa,
                    prepTime: '10-15 mins',
                    description: 'Classic potato-pea samosa fried to order, served with green chutney.',
                }),
                item({
                    name: 'Dal Samosa',
                    foodType: 'Veg',
                    price: 40,
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Indori-style samosa with a coarse spiced chana dal filling.',
                }),
                item({
                    name: 'Mawa Kachori',
                    foodType: 'Veg',
                    price: 79,
                    tag: 'sweet',
                    prepTime: '10-15 mins',
                    description: 'Sweet kachori filled with khoya and dry fruits, dipped in saffron syrup.',
                }),
            ],
        }),
        category({
            name: 'Sarafa Special Sweets',
            tag: 'sweet',
            image: IMG.gulabJamun,
            items: [
                item({
                    name: 'Desi Ghee Malpua',
                    foodType: 'Veg',
                    variants: V.pieces(69, [2, 4]),
                    tag: 'sweet',
                    prepTime: '15-20 mins',
                    description: 'Pure ghee malpua finished with a rabri drizzle and pistachio slivers.',
                }),
                item({
                    name: 'Rabri Jalebi',
                    foodType: 'Veg',
                    variants: V.weight(149),
                    tag: 'sweet',
                    image: IMG.jalebi,
                    prepTime: '10-15 mins',
                    description: 'Hot jalebi paired with thick, cardamom-scented rabri.',
                }),
                item({
                    name: 'Moong Dal Halwa',
                    foodType: 'Veg',
                    variants: V.weight(179),
                    tag: 'sweet',
                    image: IMG.halwa,
                    prepTime: '10-15 mins',
                    description: 'Slow-roasted moong dal halwa loaded with ghee, khoya and almonds.',
                }),
                item({
                    name: 'Gulab Jamun',
                    foodType: 'Veg',
                    variants: V.pieces(59, [2, 4]),
                    tag: 'sweet',
                    image: IMG.gulabJamun,
                    prepTime: '5-10 mins',
                    description: 'Khoya jamuns soaked warm in rose-cardamom syrup.',
                }),
                item({
                    name: 'Kesar Shrikhand',
                    foodType: 'Veg',
                    price: 99,
                    tag: 'sweet',
                    prepTime: '5-10 mins',
                    description: 'Hung curd whipped with saffron, sugar and green cardamom.',
                }),
            ],
        }),
        category({
            name: 'Shakes & Thandai',
            tag: 'beverage',
            items: [
                item({
                    name: 'Sarafa Special Lassi',
                    foodType: 'Veg',
                    variants: V.glass(79),
                    tag: 'beverage',
                    image: IMG.lassi,
                    prepTime: '5-10 mins',
                    description: 'Thick sweet lassi topped with malai, crushed pista and a saffron strand.',
                }),
                item({
                    name: 'Mawa Shake',
                    foodType: 'Veg',
                    variants: V.glass(99),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Chilled milk blended with khoya, dry fruits and a hint of cardamom.',
                }),
                item({
                    name: 'Kesar Thandai',
                    foodType: 'Veg',
                    variants: V.glass(89),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Cooling almond-fennel-saffron thandai, a Sarafa evening staple.',
                }),
                item({
                    name: 'Cold Coffee',
                    foodType: 'Veg',
                    variants: V.glass(89),
                    tag: 'beverage',
                    image: IMG.coldCoffee,
                    prepTime: '5-10 mins',
                    description: 'Frothy cold coffee blended with vanilla ice cream.',
                }),
                item({
                    name: 'Rose Falooda',
                    foodType: 'Veg',
                    price: 129,
                    tag: 'dessert',
                    prepTime: '10-15 mins',
                    description: 'Layered rose syrup, sabja seeds, falooda sev and kulfi.',
                }),
            ],
        }),
        category({
            name: 'Sandwich & Toast Corner',
            tag: 'snack',
            items: [
                item({
                    name: 'Bhutte Ka Kees Sandwich',
                    foodType: 'Veg',
                    price: 99,
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Indore-only grilled sandwich stuffed with creamy bhutte ka kees.',
                }),
                item({
                    name: 'Grilled Veg Sandwich',
                    foodType: 'Veg',
                    variants: V.pieces(89, [2, 4]),
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Buttered grilled sandwich with potato, beetroot, cucumber and chutney.',
                }),
                item({
                    name: 'Cheese Chilli Toast',
                    foodType: 'Veg',
                    price: 119,
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Open toast loaded with molten cheese, green chilli and oregano.',
                }),
                item({
                    name: 'Masala Toast Sandwich',
                    foodType: 'Veg',
                    price: 79,
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Bombay-style masala toast with spiced potato and mint chutney.',
                }),
            ],
        }),
    ],

    /* ========================= 2. Vijay Nagar Tandoor House (mixed) ========================= */
    vijay_nagar_tandoor: [
        category({
            name: 'Tandoori Starters',
            tag: 'starter',
            image: IMG.paneerTikka,
            items: [
                item({
                    name: 'Paneer Tikka',
                    foodType: 'Veg',
                    variants: V.pieces(279, [6, 10]),
                    tag: 'starter',
                    image: IMG.paneerTikka,
                    prepTime: '20-25 mins',
                    description: 'Malai paneer cubes marinated in hung curd and ajwain, charred in the clay oven.',
                }),
                item({
                    name: 'Murgh Malai Tikka',
                    foodType: 'Non-Veg',
                    variants: V.pieces(329, [6, 10]),
                    tag: 'starter',
                    image: IMG.seekhKebab,
                    prepTime: '25-30 mins',
                    description: 'Boneless chicken in a cream-cheese-cardamom marinade, cooked till just set.',
                }),
                item({
                    name: 'Tandoori Chicken',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(349),
                    tag: 'starter',
                    prepTime: '25-30 mins',
                    description: 'Overnight-marinated chicken on the bone, smoked over charcoal.',
                }),
                item({
                    name: 'Hara Bhara Kebab',
                    foodType: 'Veg',
                    variants: V.pieces(229, [4, 8]),
                    tag: 'starter',
                    prepTime: '15-20 mins',
                    description: 'Spinach, green pea and paneer patties shallow-fried and served with mint chutney.',
                }),
                item({
                    name: 'Mutton Seekh Kebab',
                    foodType: 'Non-Veg',
                    variants: V.pieces(379, [4, 8]),
                    tag: 'starter',
                    image: IMG.seekhKebab,
                    prepTime: '25-30 mins',
                    description: 'Minced mutton seekhs with browned onion and garam masala, grilled on skewers.',
                }),
                item({
                    name: 'Soya Chaap Tikka',
                    foodType: 'Veg',
                    variants: V.pieces(249, [4, 8]),
                    tag: 'starter',
                    prepTime: '20-25 mins',
                    description: 'Malai soya chaap sticks charred in the tandoor and tossed in chaat masala.',
                }),
            ],
        }),
        category({
            name: 'Curry Classics',
            tag: 'curry',
            image: IMG.butterChicken,
            items: [
                item({
                    name: 'Butter Chicken',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(329),
                    tag: 'curry',
                    image: IMG.butterChicken,
                    prepTime: '20-25 mins',
                    description: 'Tandoori chicken simmered in a tomato-cashew makhani gravy finished with white butter.',
                }),
                item({
                    name: 'Paneer Butter Masala',
                    foodType: 'Veg',
                    variants: V.halfFull(289),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Soft paneer in a mildly sweet makhani gravy with kasuri methi.',
                }),
                item({
                    name: 'Dal Makhani',
                    foodType: 'Veg',
                    variants: V.halfFull(239),
                    tag: 'curry',
                    image: IMG.dalMakhani,
                    prepTime: '20-25 mins',
                    description: 'Black urad dal simmered overnight with butter, cream and tomato.',
                }),
                item({
                    name: 'Kadhai Chicken',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(319),
                    tag: 'curry',
                    prepTime: '25-30 mins',
                    description: 'Chicken tossed with capsicum, onion and hand-pounded kadhai masala.',
                }),
                item({
                    name: 'Mutton Rogan Josh',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(419),
                    tag: 'curry',
                    prepTime: '30-35 mins',
                    description: 'Slow-cooked mutton in a Kashmiri chilli and fennel gravy.',
                }),
                item({
                    name: 'Malai Kofta',
                    foodType: 'Veg',
                    variants: V.halfFull(279),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Paneer-potato dumplings in a rich cashew and saffron gravy.',
                }),
            ],
        }),
        category({
            name: 'Breads from the Tandoor',
            tag: 'bread',
            image: IMG.naan,
            items: [
                item({
                    name: 'Butter Naan',
                    foodType: 'Veg',
                    price: 55,
                    tag: 'bread',
                    image: IMG.naan,
                    prepTime: '10-15 mins',
                    description: 'Refined flour naan brushed with white butter, straight off the tandoor wall.',
                }),
                item({
                    name: 'Garlic Naan',
                    foodType: 'Veg',
                    price: 75,
                    tag: 'bread',
                    prepTime: '10-15 mins',
                    description: 'Naan studded with chopped garlic and coriander.',
                }),
                item({
                    name: 'Laccha Paratha',
                    foodType: 'Veg',
                    price: 65,
                    tag: 'bread',
                    image: IMG.paratha,
                    prepTime: '10-15 mins',
                    description: 'Multi-layered whole wheat paratha, crisp outside and flaky within.',
                }),
                item({
                    name: 'Tandoori Roti',
                    foodType: 'Veg',
                    price: 30,
                    tag: 'bread',
                    prepTime: '10-15 mins',
                    description: 'Plain whole wheat roti baked in the tandoor.',
                }),
                item({
                    name: 'Amritsari Cheese Kulcha',
                    foodType: 'Veg',
                    price: 95,
                    tag: 'bread',
                    prepTime: '15-20 mins',
                    description: 'Stuffed kulcha with spiced potato and cheese, served with chole and butter.',
                }),
            ],
        }),
        category({
            name: 'Rice & Biryani',
            tag: 'rice',
            image: IMG.biryani,
            items: [
                item({
                    name: 'Chicken Dum Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(279),
                    tag: 'biryani',
                    image: IMG.biryani,
                    prepTime: '30-35 mins',
                    description: 'Long-grain basmati layered with marinated chicken and sealed for dum.',
                }),
                item({
                    name: 'Mutton Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(359),
                    tag: 'biryani',
                    prepTime: '35-40 mins',
                    description: 'Tender mutton pieces slow-cooked with saffron rice and fried onion.',
                }),
                item({
                    name: 'Veg Pulao',
                    foodType: 'Veg',
                    variants: V.halfFull(179),
                    tag: 'rice',
                    prepTime: '20-25 mins',
                    description: 'Basmati rice tossed with seasonal vegetables and whole spices.',
                }),
                item({
                    name: 'Jeera Rice',
                    foodType: 'Veg',
                    variants: V.halfFull(149),
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Steamed basmati tempered with ghee-roasted cumin.',
                }),
                item({
                    name: 'Steamed Rice',
                    foodType: 'Veg',
                    price: 119,
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Plain steamed basmati rice.',
                }),
            ],
        }),
        category({
            name: 'Desserts & Beverages',
            tag: 'dessert',
            items: [
                item({
                    name: 'Gulab Jamun',
                    foodType: 'Veg',
                    variants: V.pieces(69, [2, 4]),
                    tag: 'sweet',
                    image: IMG.gulabJamun,
                    prepTime: '5-10 mins',
                    description: 'Warm khoya jamuns in cardamom syrup.',
                }),
                item({
                    name: 'Phirni',
                    foodType: 'Veg',
                    price: 99,
                    tag: 'dessert',
                    prepTime: '5-10 mins',
                    description: 'Ground rice pudding set in a clay bowl, topped with pistachio.',
                }),
                item({
                    name: 'Masala Chaas',
                    foodType: 'Veg',
                    variants: V.glass(49),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Spiced buttermilk with roasted cumin, ginger and curry leaf.',
                }),
                item({
                    name: 'Sweet Lassi',
                    foodType: 'Veg',
                    variants: V.glass(79),
                    tag: 'beverage',
                    image: IMG.lassi,
                    prepTime: '5-10 mins',
                    description: 'Thick curd blended with sugar and topped with malai.',
                }),
                item({
                    name: 'Masala Chai',
                    foodType: 'Veg',
                    price: 39,
                    tag: 'beverage',
                    image: IMG.chai,
                    prepTime: '5-10 mins',
                    description: 'Strong cutting chai boiled with ginger, cardamom and clove.',
                }),
            ],
        }),
    ],

    /* ========================== 3. Guru Kripa Poha Jalebi (veg) ========================== */
    guru_kripa_breakfast: [
        category({
            name: 'Indori Breakfast',
            tag: 'breakfast',
            image: IMG.poha,
            items: [
                item({
                    name: 'Indori Poha',
                    foodType: 'Veg',
                    variants: V.portions(45),
                    tag: 'breakfast',
                    image: IMG.poha,
                    prepTime: '5-10 mins',
                    description: 'Steamed poha with fennel, topped with ratlami sev, onion, lemon and jeeravan masala.',
                }),
                item({
                    name: 'Poha Jalebi Combo',
                    foodType: 'Veg',
                    price: 69,
                    tag: 'breakfast',
                    prepTime: '5-10 mins',
                    description: 'The Indore classic — a plate of poha with two hot desi ghee jalebis.',
                }),
                item({
                    name: 'Usal Poha',
                    foodType: 'Veg',
                    variants: V.portions(59),
                    tag: 'breakfast',
                    prepTime: '10-15 mins',
                    description: 'Poha crowned with spicy white-pea usal gravy and raw onion.',
                }),
                item({
                    name: 'Sabudana Khichdi',
                    foodType: 'Veg',
                    variants: V.portions(69),
                    tag: 'breakfast',
                    prepTime: '10-15 mins',
                    description: 'Fasting-friendly sago tossed with peanut, potato and green chilli.',
                }),
                item({
                    name: 'Rava Upma',
                    foodType: 'Veg',
                    price: 59,
                    tag: 'breakfast',
                    prepTime: '10-15 mins',
                    description: 'Roasted semolina cooked with curry leaf, mustard and vegetables.',
                }),
            ],
        }),
        category({
            name: 'Jalebi & Sweets',
            tag: 'sweet',
            image: IMG.jalebi,
            items: [
                item({
                    name: 'Desi Ghee Jalebi',
                    foodType: 'Veg',
                    variants: V.weight(129),
                    tag: 'sweet',
                    image: IMG.jalebi,
                    prepTime: '10-15 mins',
                    description: 'Fermented batter jalebi fried in pure ghee and soaked in light syrup.',
                }),
                item({
                    name: 'Jalebi with Rabri',
                    foodType: 'Veg',
                    price: 119,
                    tag: 'sweet',
                    prepTime: '10-15 mins',
                    description: 'Crisp jalebi served over a bed of chilled thick rabri.',
                }),
                item({
                    name: 'Imarti',
                    foodType: 'Veg',
                    variants: V.weight(139),
                    tag: 'sweet',
                    prepTime: '10-15 mins',
                    description: 'Urad dal imarti, denser and less sweet than jalebi.',
                }),
                item({
                    name: 'Mawa Bati',
                    foodType: 'Veg',
                    variants: V.pieces(59, [2, 4]),
                    tag: 'sweet',
                    prepTime: '10-15 mins',
                    description: 'Malwa-style khoya dumpling stuffed with dry fruit and dipped in syrup.',
                }),
                item({
                    name: 'Malpua',
                    foodType: 'Veg',
                    variants: V.pieces(69, [2, 4]),
                    tag: 'sweet',
                    prepTime: '15-20 mins',
                    description: 'Ghee-fried malpua finished with rabri and pistachio.',
                }),
            ],
        }),
        category({
            name: 'Parathas & Sabzi',
            tag: 'bread',
            image: IMG.paratha,
            items: [
                item({
                    name: 'Aloo Paratha',
                    foodType: 'Veg',
                    variants: V.pieces(69, [1, 2]),
                    tag: 'bread',
                    image: IMG.paratha,
                    prepTime: '15-20 mins',
                    description: 'Stuffed potato paratha served with white butter, curd and pickle.',
                }),
                item({
                    name: 'Paneer Paratha',
                    foodType: 'Veg',
                    variants: V.pieces(99, [1, 2]),
                    tag: 'bread',
                    prepTime: '15-20 mins',
                    description: 'Fresh paneer stuffing with green chilli and coriander, griddled in ghee.',
                }),
                item({
                    name: 'Gobhi Paratha',
                    foodType: 'Veg',
                    variants: V.pieces(79, [1, 2]),
                    tag: 'bread',
                    prepTime: '15-20 mins',
                    description: 'Grated cauliflower stuffing with carom seeds and ginger.',
                }),
                item({
                    name: 'Mix Veg Paratha with Curd',
                    foodType: 'Veg',
                    price: 109,
                    tag: 'bread',
                    prepTime: '15-20 mins',
                    description: 'Seasonal vegetable stuffed paratha with a bowl of set curd.',
                }),
            ],
        }),
        category({
            name: 'Tea & Coffee',
            tag: 'beverage',
            image: IMG.chai,
            items: [
                item({
                    name: 'Kadak Masala Chai',
                    foodType: 'Veg',
                    variants: V.glass(29),
                    tag: 'beverage',
                    image: IMG.chai,
                    prepTime: '5-10 mins',
                    description: 'Full-boil chai with fresh masala, served scalding hot.',
                }),
                item({
                    name: 'Adrak Chai',
                    foodType: 'Veg',
                    variants: V.glass(29),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Ginger-forward tea for Indore winter mornings.',
                }),
                item({
                    name: 'South Indian Filter Coffee',
                    foodType: 'Veg',
                    variants: V.glass(59),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Decoction-brewed coffee frothed with hot milk.',
                }),
                item({
                    name: 'Cold Coffee',
                    foodType: 'Veg',
                    variants: V.glass(89),
                    tag: 'beverage',
                    image: IMG.coldCoffee,
                    prepTime: '5-10 mins',
                    description: 'Blended cold coffee with a scoop of vanilla ice cream.',
                }),
                item({
                    name: 'Green Tea',
                    foodType: 'Veg',
                    price: 49,
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Whole-leaf green tea with a wedge of lemon.',
                }),
            ],
        }),
        category({
            name: 'Namkeen Counter',
            tag: 'snack',
            items: [
                item({
                    name: 'Indori Sev',
                    foodType: 'Veg',
                    variants: V.weight(89),
                    tag: 'snack',
                    prepTime: '5-10 mins',
                    description: 'Fine besan sev, the topping that goes on nearly everything in Indore.',
                }),
                item({
                    name: 'Ratlami Sev',
                    foodType: 'Veg',
                    variants: V.weight(109),
                    tag: 'snack',
                    prepTime: '5-10 mins',
                    description: 'Thick clove-and-pepper spiked sev from Ratlam.',
                }),
                item({
                    name: 'Indori Mixture Namkeen',
                    foodType: 'Veg',
                    variants: V.weight(119),
                    tag: 'snack',
                    prepTime: '5-10 mins',
                    description: 'Sev, boondi, peanut, cornflake and curry leaf mixture.',
                }),
                item({
                    name: 'Aloo Bhujia',
                    foodType: 'Veg',
                    variants: V.weight(99),
                    tag: 'snack',
                    prepTime: '5-10 mins',
                    description: 'Crisp potato bhujia with a mild chilli finish.',
                }),
            ],
        }),
    ],

    /* ========================= 4. Bhawarkuan Biryani Adda (non-veg) ========================= */
    bhawarkuan_biryani: [
        category({
            name: 'Signature Biryani',
            tag: 'biryani',
            image: IMG.biryani,
            items: [
                item({
                    name: 'Hyderabadi Chicken Dum Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(279),
                    tag: 'biryani',
                    image: IMG.biryani,
                    prepTime: '30-35 mins',
                    description: 'Kacchi-style dum biryani with bone-in chicken, saffron milk and fried onion.',
                }),
                item({
                    name: 'Mutton Dum Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(379),
                    tag: 'biryani',
                    prepTime: '35-40 mins',
                    description: 'Aged basmati layered with marinated mutton and sealed with dough.',
                }),
                item({
                    name: 'Chicken Tikka Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(309),
                    tag: 'biryani',
                    prepTime: '30-35 mins',
                    description: 'Charred chicken tikka folded through spiced biryani rice.',
                }),
                item({
                    name: 'Boneless Chicken Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(299),
                    tag: 'biryani',
                    prepTime: '30-35 mins',
                    description: 'All-boneless chicken biryani, the easiest one to eat on the go.',
                }),
                item({
                    name: 'Egg Biryani',
                    foodType: 'Non-Veg',
                    variants: V.biryani(199),
                    tag: 'biryani',
                    prepTime: '25-30 mins',
                    description: 'Dum biryani with two whole masala-coated boiled eggs.',
                }),
            ],
        }),
        category({
            name: 'Kebab Platter',
            tag: 'starter',
            image: IMG.seekhKebab,
            items: [
                item({
                    name: 'Chicken Seekh Kebab',
                    foodType: 'Non-Veg',
                    variants: V.pieces(279, [4, 8]),
                    tag: 'starter',
                    image: IMG.seekhKebab,
                    prepTime: '25-30 mins',
                    description: 'Minced chicken seekhs grilled over charcoal, served with onion and lemon.',
                }),
                item({
                    name: 'Mutton Galouti Kebab',
                    foodType: 'Non-Veg',
                    variants: V.pieces(349, [4, 8]),
                    tag: 'starter',
                    prepTime: '25-30 mins',
                    description: 'Melt-in-mouth minced mutton patties with kewra and saffron, served with warqi paratha.',
                }),
                item({
                    name: 'Chicken Malai Tikka',
                    foodType: 'Non-Veg',
                    variants: V.pieces(299, [6, 10]),
                    tag: 'starter',
                    prepTime: '25-30 mins',
                    description: 'Cream and cheese marinated boneless chicken, gently charred.',
                }),
                item({
                    name: 'Fish Tikka',
                    foodType: 'Non-Veg',
                    variants: V.pieces(329, [4, 8]),
                    tag: 'starter',
                    image: IMG.fishTikka,
                    prepTime: '25-30 mins',
                    description: 'Basa cubes in an ajwain-carom marinade, finished in the tandoor.',
                }),
                item({
                    name: 'Chicken 65',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(269),
                    tag: 'starter',
                    image: IMG.friedChicken,
                    prepTime: '20-25 mins',
                    description: 'Crisp fried chicken tossed with curry leaf, red chilli and yoghurt.',
                }),
            ],
        }),
        category({
            name: 'Curries & Korma',
            tag: 'curry',
            image: IMG.butterChicken,
            items: [
                item({
                    name: 'Chicken Korma',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(319),
                    tag: 'curry',
                    prepTime: '25-30 mins',
                    description: 'Mughlai korma with cashew, poppy seed and yoghurt gravy.',
                }),
                item({
                    name: 'Mutton Rogan Josh',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(429),
                    tag: 'curry',
                    prepTime: '30-35 mins',
                    description: 'Kashmiri-style mutton curry with ratanjot and dried ginger.',
                }),
                item({
                    name: 'Butter Chicken',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(339),
                    tag: 'curry',
                    image: IMG.butterChicken,
                    prepTime: '25-30 mins',
                    description: 'Makhani gravy chicken with a generous butter finish.',
                }),
                item({
                    name: 'Egg Curry',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(199),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Boiled eggs simmered in an onion-tomato masala.',
                }),
                item({
                    name: 'Chicken Handi',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(329),
                    tag: 'curry',
                    prepTime: '25-30 mins',
                    description: 'Chicken slow-cooked in a sealed handi with cream and whole spices.',
                }),
            ],
        }),
        category({
            name: 'Breads & Rice',
            tag: 'bread',
            image: IMG.naan,
            items: [
                item({
                    name: 'Butter Naan',
                    foodType: 'Veg',
                    price: 55,
                    tag: 'bread',
                    image: IMG.naan,
                    prepTime: '10-15 mins',
                    description: 'Tandoor naan brushed with butter.',
                }),
                item({
                    name: 'Rumali Roti',
                    foodType: 'Veg',
                    variants: V.pieces(35, [2, 4]),
                    tag: 'bread',
                    prepTime: '10-15 mins',
                    description: 'Paper-thin handkerchief roti, the traditional kebab partner.',
                }),
                item({
                    name: 'Tandoori Roti',
                    foodType: 'Veg',
                    price: 30,
                    tag: 'bread',
                    prepTime: '10-15 mins',
                    description: 'Whole wheat roti baked against the tandoor wall.',
                }),
                item({
                    name: 'Jeera Rice',
                    foodType: 'Veg',
                    variants: V.halfFull(149),
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Basmati rice tempered with ghee and cumin.',
                }),
                item({
                    name: 'Steamed Rice',
                    foodType: 'Veg',
                    price: 119,
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Plain steamed basmati.',
                }),
            ],
        }),
        category({
            name: 'Sides & Raita',
            tag: 'addon',
            image: IMG.raita,
            items: [
                item({
                    name: 'Mirchi Ka Salan',
                    foodType: 'Veg',
                    price: 99,
                    tag: 'curry',
                    prepTime: '10-15 mins',
                    description: 'The classic biryani companion — peanut, sesame and tamarind chilli gravy.',
                }),
                item({
                    name: 'Boondi Raita',
                    foodType: 'Veg',
                    variants: V.halfFull(69),
                    tag: 'addon',
                    image: IMG.raita,
                    prepTime: '5-10 mins',
                    description: 'Whisked curd with soaked boondi and roasted cumin.',
                }),
                item({
                    name: 'Onion Lachcha Salad',
                    foodType: 'Veg',
                    price: 49,
                    tag: 'addon',
                    prepTime: '5-10 mins',
                    description: 'Sliced onion with lemon, green chilli and chaat masala.',
                }),
                item({
                    name: 'Double Ka Meetha',
                    foodType: 'Veg',
                    price: 119,
                    tag: 'dessert',
                    prepTime: '10-15 mins',
                    description: 'Hyderabadi bread pudding soaked in saffron milk and ghee.',
                }),
                item({
                    name: 'Shahi Tukda',
                    foodType: 'Veg',
                    price: 129,
                    tag: 'dessert',
                    prepTime: '10-15 mins',
                    description: 'Fried bread in rabri, garnished with almond and silver leaf.',
                }),
            ],
        }),
    ],

    /* ========================= 5. Nipania Pizza & Pasta Co. (mixed) ========================= */
    nipania_pizza: [
        category({
            name: 'Wood Fired Pizzas',
            tag: 'pizza',
            image: IMG.margherita,
            items: [
                item({
                    name: 'Wood Fired Margherita',
                    foodType: 'Veg',
                    variants: V.pizza(249),
                    tag: 'pizza',
                    image: IMG.margherita,
                    prepTime: '20-25 mins',
                    description: 'San Marzano tomato base, fresh mozzarella and torn basil on a 48-hour dough.',
                }),
                item({
                    name: 'Farmhouse Pizza',
                    foodType: 'Veg',
                    variants: V.pizza(299),
                    tag: 'pizza',
                    prepTime: '20-25 mins',
                    description: 'Onion, capsicum, tomato, mushroom and sweet corn over mozzarella.',
                }),
                item({
                    name: 'Peri Peri Chicken Pizza',
                    foodType: 'Non-Veg',
                    variants: V.pizza(349),
                    tag: 'pizza',
                    image: IMG.pepperoniStyle,
                    prepTime: '25-30 mins',
                    description: 'Grilled peri peri chicken, red onion and jalapeno with a chilli-oil drizzle.',
                }),
                item({
                    name: 'Chicken Tikka Pizza',
                    foodType: 'Non-Veg',
                    variants: V.pizza(359),
                    tag: 'pizza',
                    prepTime: '25-30 mins',
                    description: 'Tandoori chicken tikka on a makhani base with onion and coriander.',
                }),
                item({
                    name: 'Paneer Makhani Pizza',
                    foodType: 'Veg',
                    variants: V.pizza(319),
                    tag: 'pizza',
                    prepTime: '20-25 mins',
                    description: 'Makhani sauce, tandoori paneer and capsicum with a kasuri methi finish.',
                }),
                item({
                    name: 'Four Cheese Pizza',
                    foodType: 'Veg',
                    variants: V.pizza(379),
                    tag: 'pizza',
                    prepTime: '20-25 mins',
                    description: 'Mozzarella, cheddar, parmesan and a blue-cheese crumble.',
                }),
            ],
        }),
        category({
            name: 'Pasta & Risotto',
            tag: 'pasta',
            image: IMG.pasta,
            items: [
                item({
                    name: 'Penne Alfredo',
                    foodType: 'Veg',
                    variants: V.portions(279),
                    tag: 'pasta',
                    image: IMG.pasta,
                    prepTime: '20-25 mins',
                    description: 'Penne in a parmesan cream sauce with cracked black pepper.',
                }),
                item({
                    name: 'Penne Arrabbiata',
                    foodType: 'Veg',
                    variants: V.portions(259),
                    tag: 'pasta',
                    prepTime: '20-25 mins',
                    description: 'Spicy tomato-garlic sauce with chilli flakes and fresh basil.',
                }),
                item({
                    name: 'Chicken Lasagne',
                    foodType: 'Non-Veg',
                    price: 379,
                    tag: 'pasta',
                    prepTime: '25-30 mins',
                    description: 'Layered pasta sheets with chicken ragu, bechamel and baked mozzarella.',
                }),
                item({
                    name: 'Basil Pesto Pasta',
                    foodType: 'Veg',
                    variants: V.portions(299),
                    tag: 'pasta',
                    prepTime: '20-25 mins',
                    description: 'Fusilli tossed in house-made basil-pinenut pesto.',
                }),
                item({
                    name: 'Mushroom Risotto',
                    foodType: 'Veg',
                    price: 349,
                    tag: 'pasta',
                    prepTime: '25-30 mins',
                    description: 'Arborio rice slow-stirred with button mushroom, white wine and parmesan.',
                }),
            ],
        }),
        category({
            name: 'Garlic Bread & Sides',
            tag: 'snack',
            image: IMG.garlicBread,
            items: [
                item({
                    name: 'Garlic Bread',
                    foodType: 'Veg',
                    variants: V.pieces(129, [4, 8]),
                    tag: 'snack',
                    image: IMG.garlicBread,
                    prepTime: '15-20 mins',
                    description: 'Oven-baked baguette slices with garlic butter and herbs.',
                }),
                item({
                    name: 'Cheesy Garlic Bread',
                    foodType: 'Veg',
                    variants: V.pieces(169, [4, 8]),
                    tag: 'snack',
                    prepTime: '15-20 mins',
                    description: 'Garlic bread loaded with molten mozzarella and chilli flakes.',
                }),
                item({
                    name: 'Peri Peri Fries',
                    foodType: 'Veg',
                    variants: V.portions(139),
                    tag: 'snack',
                    image: IMG.fries,
                    prepTime: '10-15 mins',
                    description: 'Crisp fries dusted with peri peri seasoning.',
                }),
                item({
                    name: 'Loaded Cheese Nachos',
                    foodType: 'Veg',
                    price: 199,
                    tag: 'snack',
                    prepTime: '15-20 mins',
                    description: 'Corn nachos with cheese sauce, salsa, jalapeno and olives.',
                }),
                item({
                    name: 'Onion Rings',
                    foodType: 'Veg',
                    variants: V.pieces(129, [6, 12]),
                    tag: 'snack',
                    prepTime: '10-15 mins',
                    description: 'Beer-battered onion rings with a smoky dip.',
                }),
            ],
        }),
        category({
            name: 'Burgers & Wraps',
            tag: 'snack',
            image: IMG.burger,
            items: [
                item({
                    name: 'Classic Veg Burger',
                    foodType: 'Veg',
                    price: 149,
                    tag: 'snack',
                    image: IMG.burger,
                    prepTime: '15-20 mins',
                    description: 'Crumb-fried potato patty with lettuce, tomato and burger sauce.',
                }),
                item({
                    name: 'Crispy Chicken Burger',
                    foodType: 'Non-Veg',
                    price: 199,
                    tag: 'snack',
                    prepTime: '15-20 mins',
                    description: 'Buttermilk-fried chicken thigh with slaw and spicy mayo.',
                }),
                item({
                    name: 'Paneer Tikka Wrap',
                    foodType: 'Veg',
                    price: 179,
                    tag: 'snack',
                    prepTime: '15-20 mins',
                    description: 'Tandoori paneer, onion and mint mayo rolled in a soft tortilla.',
                }),
                item({
                    name: 'Chicken Shawarma Wrap',
                    foodType: 'Non-Veg',
                    price: 209,
                    tag: 'snack',
                    prepTime: '15-20 mins',
                    description: 'Shaved chicken with garlic toum, pickles and fries in pita.',
                }),
            ],
        }),
        category({
            name: 'Desserts & Beverages',
            tag: 'dessert',
            image: IMG.lavaCake,
            items: [
                item({
                    name: 'Choco Lava Cake',
                    foodType: 'Veg',
                    variants: V.pieces(129, [1, 2]),
                    tag: 'dessert',
                    image: IMG.lavaCake,
                    prepTime: '10-15 mins',
                    description: 'Warm chocolate cake with a molten centre.',
                }),
                item({
                    name: 'Tiramisu',
                    foodType: 'Veg',
                    price: 219,
                    tag: 'dessert',
                    image: IMG.tiramisu,
                    prepTime: '5-10 mins',
                    description: 'Coffee-soaked savoiardi layered with mascarpone and cocoa.',
                }),
                item({
                    name: 'Brownie with Ice Cream',
                    foodType: 'Veg',
                    price: 189,
                    tag: 'dessert',
                    prepTime: '10-15 mins',
                    description: 'Warm walnut brownie with a scoop of vanilla and chocolate sauce.',
                }),
                item({
                    name: 'Iced Latte',
                    foodType: 'Veg',
                    variants: V.glass(159),
                    tag: 'beverage',
                    image: IMG.coldCoffee,
                    prepTime: '5-10 mins',
                    description: 'Double-shot espresso over cold milk and ice.',
                }),
                item({
                    name: 'Virgin Mojito',
                    foodType: 'Veg',
                    variants: V.glass(129),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Lime, mint and soda over crushed ice.',
                }),
            ],
        }),
    ],

    /* ============================== 6. Saket Wok House (mixed) ============================== */
    saket_wok: [
        category({
            name: 'Momos Station',
            tag: 'momo',
            image: IMG.momos,
            items: [
                item({
                    name: 'Veg Steamed Momos',
                    foodType: 'Veg',
                    variants: V.pieces(99, [6, 10]),
                    tag: 'momo',
                    image: IMG.momos,
                    prepTime: '15-20 mins',
                    description: 'Hand-pleated cabbage and carrot momos with a fiery red chutney.',
                }),
                item({
                    name: 'Chicken Steamed Momos',
                    foodType: 'Non-Veg',
                    variants: V.pieces(129, [6, 10]),
                    tag: 'momo',
                    prepTime: '15-20 mins',
                    description: 'Minced chicken and spring onion filling, steamed to order.',
                }),
                item({
                    name: 'Veg Fried Momos',
                    foodType: 'Veg',
                    variants: V.pieces(119, [6, 10]),
                    tag: 'momo',
                    prepTime: '15-20 mins',
                    description: 'Deep-fried momos tossed in schezwan sauce.',
                }),
                item({
                    name: 'Chicken Tandoori Momos',
                    foodType: 'Non-Veg',
                    variants: V.pieces(169, [6, 10]),
                    tag: 'momo',
                    prepTime: '20-25 mins',
                    description: 'Momos coated in tandoori marinade and charred, served with mint mayo.',
                }),
                item({
                    name: 'Paneer Momos',
                    foodType: 'Veg',
                    variants: V.pieces(139, [6, 10]),
                    tag: 'momo',
                    prepTime: '15-20 mins',
                    description: 'Crumbled paneer, ginger and pepper filling in a thin wrapper.',
                }),
            ],
        }),
        category({
            name: 'Wok Noodles',
            tag: 'chinese',
            image: IMG.noodles,
            items: [
                item({
                    name: 'Veg Hakka Noodles',
                    foodType: 'Veg',
                    variants: V.halfFull(159),
                    tag: 'chinese',
                    image: IMG.noodles,
                    prepTime: '15-20 mins',
                    description: 'Wok-tossed noodles with julienned vegetables and dark soy.',
                }),
                item({
                    name: 'Chilli Garlic Wok Noodles',
                    foodType: 'Veg',
                    variants: V.halfFull(179),
                    tag: 'chinese',
                    prepTime: '15-20 mins',
                    description: 'Noodles in a hot garlic sauce with burnt chilli and spring onion.',
                }),
                item({
                    name: 'Chicken Schezwan Noodles',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(219),
                    tag: 'chinese',
                    prepTime: '20-25 mins',
                    description: 'Shredded chicken tossed with house schezwan paste and noodles.',
                }),
                item({
                    name: 'Pan Fried Noodles',
                    foodType: 'Veg',
                    variants: V.halfFull(199),
                    tag: 'chinese',
                    prepTime: '20-25 mins',
                    description: 'Crisp noodle nest topped with a glossy vegetable gravy.',
                }),
                item({
                    name: 'Singapore Chilli Noodles',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(229),
                    tag: 'chinese',
                    prepTime: '20-25 mins',
                    description: 'Curry-spiced rice noodles with egg, chicken and bean sprouts.',
                }),
            ],
        }),
        category({
            name: 'Fried Rice',
            tag: 'rice',
            image: IMG.friedRice,
            items: [
                item({
                    name: 'Veg Fried Rice',
                    foodType: 'Veg',
                    variants: V.halfFull(149),
                    tag: 'rice',
                    image: IMG.friedRice,
                    prepTime: '15-20 mins',
                    description: 'High-flame fried rice with beans, carrot and spring onion.',
                }),
                item({
                    name: 'Chicken Fried Rice',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(199),
                    tag: 'rice',
                    prepTime: '20-25 mins',
                    description: 'Fried rice with diced chicken and scrambled egg.',
                }),
                item({
                    name: 'Schezwan Fried Rice',
                    foodType: 'Veg',
                    variants: V.halfFull(179),
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Fried rice tossed in schezwan paste — hot, and meant to be.',
                }),
                item({
                    name: 'Burnt Garlic Fried Rice',
                    foodType: 'Veg',
                    variants: V.halfFull(169),
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Rice tossed with crisp fried garlic and light soy.',
                }),
                item({
                    name: 'Triple Schezwan Rice',
                    foodType: 'Non-Veg',
                    price: 289,
                    tag: 'rice',
                    prepTime: '25-30 mins',
                    description: 'Fried rice, noodles and schezwan gravy topped with a fried egg.',
                }),
            ],
        }),
        category({
            name: 'Starters & Chilli',
            tag: 'starter',
            image: IMG.manchurian,
            items: [
                item({
                    name: 'Veg Manchurian Dry',
                    foodType: 'Veg',
                    variants: V.halfFull(179),
                    tag: 'starter',
                    image: IMG.manchurian,
                    prepTime: '20-25 mins',
                    description: 'Fried vegetable dumplings tossed in a sticky garlic-soy glaze.',
                }),
                item({
                    name: 'Chilli Paneer',
                    foodType: 'Veg',
                    variants: V.halfFull(219),
                    tag: 'starter',
                    prepTime: '20-25 mins',
                    description: 'Batter-fried paneer with capsicum, onion and green chilli.',
                }),
                item({
                    name: 'Chilli Chicken',
                    foodType: 'Non-Veg',
                    variants: V.halfFull(249),
                    tag: 'starter',
                    prepTime: '20-25 mins',
                    description: 'Indo-Chinese chilli chicken, dry and generously peppered.',
                }),
                item({
                    name: 'Honey Chilli Potato',
                    foodType: 'Veg',
                    variants: V.halfFull(169),
                    tag: 'starter',
                    prepTime: '15-20 mins',
                    description: 'Crisp potato batons in honey, chilli and toasted sesame.',
                }),
                item({
                    name: 'Crispy Corn',
                    foodType: 'Veg',
                    price: 189,
                    tag: 'starter',
                    prepTime: '15-20 mins',
                    description: 'Fried sweet corn kernels tossed with curry leaf and chilli.',
                }),
                item({
                    name: 'Drums of Heaven',
                    foodType: 'Non-Veg',
                    variants: V.pieces(279, [4, 8]),
                    tag: 'starter',
                    image: IMG.friedChicken,
                    prepTime: '25-30 mins',
                    description: 'Chicken lollipops in a sweet-hot schezwan coating.',
                }),
            ],
        }),
        category({
            name: 'Thai & Soups',
            tag: 'soup',
            image: IMG.soup,
            items: [
                item({
                    name: 'Thai Red Curry with Rice',
                    foodType: 'Veg',
                    price: 289,
                    tag: 'thaiCurry',
                    image: IMG.thaiCurry,
                    prepTime: '25-30 mins',
                    description: 'Red curry paste and coconut milk with vegetables, served with jasmine rice.',
                }),
                item({
                    name: 'Thai Green Curry with Rice',
                    foodType: 'Non-Veg',
                    price: 329,
                    tag: 'thaiCurry',
                    prepTime: '25-30 mins',
                    description: 'Chicken in a green curry of galangal, basil and coconut milk.',
                }),
                item({
                    name: 'Veg Manchow Soup',
                    foodType: 'Veg',
                    variants: V.glass(119),
                    tag: 'soup',
                    image: IMG.soup,
                    prepTime: '10-15 mins',
                    description: 'Peppery vegetable soup topped with fried noodles.',
                }),
                item({
                    name: 'Chicken Hot & Sour Soup',
                    foodType: 'Non-Veg',
                    variants: V.glass(149),
                    tag: 'soup',
                    prepTime: '10-15 mins',
                    description: 'Vinegar-and-white-pepper soup with shredded chicken.',
                }),
                item({
                    name: 'Sweet Corn Soup',
                    foodType: 'Veg',
                    variants: V.glass(119),
                    tag: 'soup',
                    prepTime: '10-15 mins',
                    description: 'Creamed sweet corn soup with a touch of white pepper.',
                }),
            ],
        }),
    ],

    /* ============================== 7. Rau Punjabi Rasoi (veg) ============================== */
    rau_punjabi: [
        category({
            name: 'Thali Specials',
            tag: 'thali',
            image: IMG.thali,
            items: [
                item({
                    name: 'Punjabi Special Thali',
                    foodType: 'Veg',
                    price: 229,
                    tag: 'thali',
                    image: IMG.thali,
                    prepTime: '20-25 mins',
                    description: 'Two sabzi, dal makhani, rice, four rotis, salad, raita, papad and a sweet.',
                }),
                item({
                    name: 'Deluxe Veg Thali',
                    foodType: 'Veg',
                    price: 299,
                    tag: 'thali',
                    prepTime: '20-25 mins',
                    description: 'Paneer sabzi, seasonal sabzi, dal, pulao, breads, raita, salad and gulab jamun.',
                }),
                item({
                    name: 'Mini Thali',
                    foodType: 'Veg',
                    price: 169,
                    tag: 'thali',
                    prepTime: '15-20 mins',
                    description: 'One sabzi, dal, rice, two rotis, salad and papad — a quick single meal.',
                }),
                item({
                    name: 'Jain Thali (No Onion No Garlic)',
                    foodType: 'Veg',
                    price: 239,
                    tag: 'thali',
                    prepTime: '20-25 mins',
                    description: 'Full thali cooked entirely without onion, garlic or root vegetables.',
                }),
            ],
        }),
        category({
            name: 'Punjabi Sabzi',
            tag: 'curry',
            image: IMG.dalMakhani,
            items: [
                item({
                    name: 'Sarson Da Saag',
                    foodType: 'Veg',
                    variants: V.halfFull(219),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Slow-cooked mustard greens finished with white butter — served with makki di roti.',
                }),
                item({
                    name: 'Dal Makhani',
                    foodType: 'Veg',
                    variants: V.halfFull(229),
                    tag: 'curry',
                    image: IMG.dalMakhani,
                    prepTime: '20-25 mins',
                    description: 'Whole black dal simmered overnight with butter and cream.',
                }),
                item({
                    name: 'Shahi Paneer',
                    foodType: 'Veg',
                    variants: V.halfFull(279),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Paneer in a cashew-cream gravy with a hint of green cardamom.',
                }),
                item({
                    name: 'Amritsari Chole',
                    foodType: 'Veg',
                    variants: V.halfFull(199),
                    tag: 'curry',
                    image: IMG.chole,
                    prepTime: '20-25 mins',
                    description: 'Dark chana masala cooked with tea leaves, anardana and ginger.',
                }),
                item({
                    name: 'Kadhi Pakora',
                    foodType: 'Veg',
                    variants: V.halfFull(179),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Tangy besan kadhi with soft onion pakoras.',
                }),
                item({
                    name: 'Aloo Gobhi Adraki',
                    foodType: 'Veg',
                    variants: V.halfFull(189),
                    tag: 'curry',
                    prepTime: '20-25 mins',
                    description: 'Dry potato-cauliflower sabzi finished with julienned ginger.',
                }),
            ],
        }),
        category({
            name: 'Rotis & Parathas',
            tag: 'bread',
            image: IMG.naan,
            items: [
                item({
                    name: 'Makki Di Roti',
                    foodType: 'Veg',
                    variants: V.pieces(45, [2, 4]),
                    tag: 'bread',
                    prepTime: '15-20 mins',
                    description: 'Hand-patted corn flour roti with a knob of white butter.',
                }),
                item({
                    name: 'Tandoori Roti',
                    foodType: 'Veg',
                    price: 30,
                    tag: 'bread',
                    prepTime: '10-15 mins',
                    description: 'Whole wheat roti from the tandoor.',
                }),
                item({
                    name: 'Missi Roti',
                    foodType: 'Veg',
                    price: 45,
                    tag: 'bread',
                    prepTime: '10-15 mins',
                    description: 'Besan and wheat roti with ajwain and onion.',
                }),
                item({
                    name: 'Amritsari Kulcha',
                    foodType: 'Veg',
                    price: 99,
                    tag: 'bread',
                    prepTime: '15-20 mins',
                    description: 'Crisp stuffed kulcha served with chole and pickled onion.',
                }),
                item({
                    name: 'Laccha Paratha',
                    foodType: 'Veg',
                    price: 65,
                    tag: 'bread',
                    image: IMG.paratha,
                    prepTime: '10-15 mins',
                    description: 'Layered whole wheat paratha, ghee-finished.',
                }),
            ],
        }),
        category({
            name: 'Rice & Pulao',
            tag: 'rice',
            items: [
                item({
                    name: 'Veg Pulao',
                    foodType: 'Veg',
                    variants: V.halfFull(179),
                    tag: 'rice',
                    prepTime: '20-25 mins',
                    description: 'Basmati cooked with seasonal vegetables and whole spices.',
                }),
                item({
                    name: 'Jeera Rice',
                    foodType: 'Veg',
                    variants: V.halfFull(149),
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Ghee-tempered cumin rice.',
                }),
                item({
                    name: 'Kashmiri Pulao',
                    foodType: 'Veg',
                    variants: V.halfFull(229),
                    tag: 'rice',
                    prepTime: '20-25 mins',
                    description: 'Sweet-savoury pulao with pineapple, pomegranate and dry fruit.',
                }),
                item({
                    name: 'Steamed Rice',
                    foodType: 'Veg',
                    price: 119,
                    tag: 'rice',
                    prepTime: '15-20 mins',
                    description: 'Plain steamed basmati rice.',
                }),
            ],
        }),
        category({
            name: 'Lassi & Sweets',
            tag: 'beverage',
            image: IMG.lassi,
            items: [
                item({
                    name: 'Punjabi Sweet Lassi',
                    foodType: 'Veg',
                    variants: V.glass(89),
                    tag: 'beverage',
                    image: IMG.lassi,
                    prepTime: '5-10 mins',
                    description: 'Thick lassi in a steel glass, topped with malai and crushed pista.',
                }),
                item({
                    name: 'Salted Lassi',
                    foodType: 'Veg',
                    variants: V.glass(69),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Churned curd with black salt and roasted cumin.',
                }),
                item({
                    name: 'Mango Lassi',
                    foodType: 'Veg',
                    variants: V.glass(109),
                    tag: 'beverage',
                    prepTime: '5-10 mins',
                    description: 'Alphonso pulp blended with sweet curd.',
                }),
                item({
                    name: 'Gajar Ka Halwa',
                    foodType: 'Veg',
                    variants: V.weight(149),
                    tag: 'sweet',
                    image: IMG.halwa,
                    prepTime: '10-15 mins',
                    description: 'Red carrot halwa slow-cooked in milk and ghee with khoya.',
                }),
                item({
                    name: 'Rice Kheer',
                    foodType: 'Veg',
                    price: 109,
                    tag: 'sweet',
                    prepTime: '10-15 mins',
                    description: 'Slow-reduced rice pudding with cardamom and almond.',
                }),
            ],
        }),
    ],
};

export const getMenuFor = (menuKey) => {
    const menu = MENUS[menuKey];
    if (!menu) throw new Error(`No menu defined for key "${menuKey}"`);
    return menu;
};
